### ISSUE TITLE
Bootstrap everything with Bootstrap

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/patata#2]

**Comment by aitorres** [comment]
I can help beautify the layout with Bootstrap, if that's okay.

**Comment by lvps** [comment]
@Hyd3L what do you think?

**Comment by aitorres** [comment]
Hello! I added a small proposal for this. I can change/modify/fix anything if needed, just let me know. Also, I kind of modified some static HTML code that was being echo'ed through php, so that it now is just plain HTML code. Just to let you know.

**Comment by 30n30n** [comment]
Uncaught TypeError: Cannot read property 'fn' of undefined
    at util.js:56
    at util.js:10
    at bootstrap.min.js:6
    at bootstrap.min.js:6

in util.js:56

**Comment by aitorres** [comment]
@30n30n Bug fixed! It was due to a missing jQuery import. I added a new PR in order to fix it.
