### ISSUE TITLE
Add social media stats

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/patata#29]
Since this monitor is already (mostly) always on, we could show some stats that are relevant to us:
- YouTube subscribers / total views
- Instagram followers
- Likes on Facebook 
- Podcast listens
- Connections(?) on LinkedIn

This should be as big a number (+ icon) as possible, so that it's actually visible, maybe achieved by rotating the different stats and only showing one at a time.

**Comment by lvps** [comment]
@e-caste Can we use stats from your yourls shortener instead? It exposes some APIs, we just need an account for the 🥔

**Comment by alecello** [comment]
@lvps How are you going to count subs and follows from that? (or is it an entirely different thing you want to display?)

**Comment by e-caste** [comment]
@lvps You can also use that data, but I don’t think it would be a valid replacement. It only contains the numbers of clicks of shortened URLs, which are interesting but not as much as what I have posted in the original comment.

**Comment by il-palmi** [comment]
Reopen it, because nothing works
